// Code generated by Prismic. DO NOT EDIT.

import CareLineSpotlight from "./CareLineSpotlight";
import Coverage from "./Coverage";
import Faq from "./Faq";
import Feature from "./Feature";
import Hero from "./Hero";
import OtherTopics from "./OtherTopics";
import Testimonials from "./Testimonials";

export const components = {
	care_line_spotlight: CareLineSpotlight,
	coverage: Coverage,
	faq: Faq,
	feature: Feature,
	hero: Hero,
	other_topics: OtherTopics,
	testimonials: Testimonials
};